### ISSUE TITLE
Is there a proxy function？

### ISSUE THREAD

**Issue by tanjunchen** [butuzov/deadlinks#41]
Google is not accessible in some places
So Maybe you can add proxy function.
Thanks

**Comment by butuzov** [comment]
> Google is not accessible in some places
> So Maybe you can add proxy function.
> Thanks

Hi @tanjunchen can you add a bit more details? What happened when you install it? How do you use it?

**Comment by tanjunchen** [comment]
@butuzov  Sure.Usually, when we access the network, sometimes we hide our IP through a proxy and use http proxy.In some places, it is impossible to access google, so some errors may occur in your url check tool, but if we add a method like http proxy, I think this detection tool is perfect.
Thanks

**Comment by butuzov** [comment]
It sounds like a nice idea, I will add it to **TODO**^ however I can't guaranty to implement it asap. If you can implement it feel free to create PR. Next few releases (0.2.*) I will only remove TD, existing bugs and add examples to documentation.
